# Generated by Django 5.0.7 on 2024-08-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="user",
        ),
    ]
