# Generated by Django 5.0.7 on 2024-08-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_alter_lead_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("nouveau", "Nouveau"),
                    ("contacté", "Contacté"),
                    ("converti", "Converti"),
                    ("perdu", "Perdu"),
                ],
                max_length=20,
            ),
        ),
    ]
