# Generated by Django 5.0.7 on 2024-08-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assigned_to',
            new_name='Assigné',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='last_name',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='first_name',
            new_name='Prénom',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='phone',
            new_name='Télephone',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='created_at',
            new_name='crée',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='status',
            new_name='statut',
        ),
    ]
