# Generated by Django 5.0.7 on 2024-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_rename_assigned_to_lead_assigné_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Site Web', 'Site Web'), ('Publicité', 'Publicité'), ('Référence', 'Référence'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
