# Generated by Django 5.0.7 on 2024-08-24 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='commentaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='duree',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('Appel', 'Appel'), ('Email', 'Email')], max_length=10),
        ),
    ]
