# Generated by Django 5.0.7 on 2024-08-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_interaction_commentaires_interaction_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
