# Generated by Django 5.0.7 on 2024-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_interaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
