# Generated by Django 5.0.7 on 2024-09-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
