# Generated by Django 5.0.7 on 2024-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='historique_appel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='historique_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
