# Generated by Django 5.0.6 on 2024-07-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leads.lead"
                    ),
                ),
            ],
        ),
    ]
