# Generated by Django 5.0.7 on 2024-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("lead", "Lead"), ("message", "Message"), ("file", "File")],
                default="lead",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
