# Generated by Django 5.0.7 on 2024-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('lead', 'Lead'), ('message', 'Message'), ('Annonce', 'annonce')], max_length=20),
        ),
    ]
