# Generated by Django 5.0.7 on 2024-09-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
